### ISSUE TITLE
FR: Replace 

### ISSUE THREAD

**Issue by brimwats** [jglev/obsidian-boost-link-suggestions#6]
I would like to always use boosted links; is there a way to replace the default [[ entirely?

**Comment by jglev** [comment]
Thank you for reaching out!

In order not to cause unintended side-effects, I've avoided overriding or otherwise affecting Obsidian's default `[[` link syntax, as, to my knowledge, the Obsidian API doesn't currently include an official way to do so. Thus, at least within the context of this plugin, I'm not currently planning to integrate a way to replace / disable the default `[[` behavior.

With that said, in case it's useful to hear, I've switched to always using boosted links in my own work, and have been able to re-train my muscle memory away from `[[` over the past week by setting a more-easily-accessible hotkey for the `Boost Link Suggestions: Trigger link` command (in my case, `Shift + Backspace`). I imagine that that won't work for every user, but my hope is that between the ability to set a hotkey and to set a trigger phrase that's near (even if not overriding) the default `[[`, each person will be able to find something that works.

(Because GitHub Issues can only be Open or Closed, I'm "closing" this thread as resolved; but please feel free to write back with any additional questions!)
